import json
import re
from typing import Any

from app.core.config import settings

try:
    from groq import Groq  # type: ignore
except Exception:  # pragma: no cover - optional dependency
    Groq = None


class GroqClient:
    def __init__(
        self,
        api_key: str | None = None,
        model: str = "llama-3.3-70b-versatile",
        use_mock: bool | None = None,
    ):
        self.api_key = api_key or settings.GROQ_API_KEY
        self.model = model
        self.use_mock = settings.DEBUG if use_mock is None else use_mock

    def chat_json(self, messages: list[dict[str, str]], mode: str = "continuation") -> dict[str, Any]:
        if self.use_mock:
            return self._mock_response(messages, mode)

        if not self.api_key or Groq is None:
            return self._mock_response(messages, mode)

        try:
            client = Groq(api_key=self.api_key)
            completion = client.chat.completions.create(
                model=self.model,
                messages=messages,
                response_format={"type": "json_object"},
                temperature=0.2,
            )
            content = completion.choices[0].message.content or "{}"
            return json.loads(content)
        except json.JSONDecodeError:
            if mode == "initial":
                return {}
            return {"message": "Invalid JSON from AI", "updated_itinerary": None}
        except Exception as e:
            return self._mock_response(messages, mode)

    def get_structured_output(self, messages: list[dict[str, str]]) -> dict[str, Any]:
        return self.chat_json(messages)

    def _mock_response(self, messages: list[dict[str, str]], mode: str = "continuation") -> dict[str, Any]:
        last_user_text = ""
        for msg in reversed(messages):
            if msg.get("role") == "user":
                last_user_text = msg.get("content", "")
                break
                
        if mode == "initial":
            days = 3
            match = re.search(r"- Days:\s*(\d+)", last_user_text)
            if match:
                days = int(match.group(1))
            
            days_plan = []
            for day in range(1, days + 1):
                if days <= 2:
                    city = "Bishkek"
                elif days <= 4:
                    city = "Bishkek" if day <= 2 else "Karakol"
                else:
                    if day <= 2:
                        city = "Bishkek"
                    elif day <= 4:
                        city = "Karakol"
                    else:
                        city = "Cholpon-Ata"

                if city == "Bishkek":
                    location = "Bishkek City Center"
                    title = "Exploring Bishkek"
                elif city == "Karakol":
                    location = "Mountain Area"
                    title = "Mountain Adventure"
                else:
                    location = "Issyk-Kul Shore"
                    title = "Lake Retreat"
                
                days_plan.append({
                    "day": day,
                    "title": title,
                    "city": city,
                    "location": location,
                    "activities": [
                        {"time": "Morning", "description": f"Mocked morning activity in {city}", "type": "sightseeing"},
                        {"time": "Afternoon", "description": f"Mocked afternoon exploration in {location}", "type": "activity"},
                        {"time": "Evening", "description": "Mocked dinner", "type": "meal"}
                    ]
                })

            return {
                "title": f"Mocked {days}-Day Trip",
                "itinerary": {
                    "summary": f"This is a mocked {days}-day trip generated by initial generation mode.",
                    "days": days_plan
                }
            }

        return {
            "message": (
                "Mock response: I updated your plan based on the latest request. "
                f"Request context: {last_user_text[:120]}"
            ),
            "updated_itinerary": {
                "status": "mock-updated",
                "updated": True,
            },
        }
