"""init models fresh

Revision ID: 284999202e63
Revises: c0e73dd7329f
Create Date: 2026-04-18 16:23:55.470315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '284999202e63'
down_revision: Union[str, Sequence[str], None] = 'c0e73dd7329f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('budget', sa.String(length=50), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('interests', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('travel_style', sa.String(length=100), nullable=False),
    sa.Column('itinerary_json', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trips_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips'))
    )
    op.create_index(op.f('ix_trips_created_at'), 'trips', ['created_at'], unique=False)
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_index(op.f('ix_trips_title'), 'trips', ['title'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_table('trip_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_messages_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_messages'))
    )
    op.create_index(op.f('ix_trip_messages_created_at'), 'trip_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_trip_messages_id'), 'trip_messages', ['id'], unique=False)
    op.create_index(op.f('ix_trip_messages_trip_id'), 'trip_messages', ['trip_id'], unique=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_index(op.f('ix_trip_messages_trip_id'), table_name='trip_messages')
    op.drop_index(op.f('ix_trip_messages_id'), table_name='trip_messages')
    op.drop_index(op.f('ix_trip_messages_created_at'), table_name='trip_messages')
    op.drop_table('trip_messages')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_title'), table_name='trips')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_created_at'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
