"""Initial migration

Revision ID: 30885ac68b09
Revises: 
Create Date: 2026-04-22 16:11:42.151731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30885ac68b09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('price_level', sa.String(length=20), nullable=False),
    sa.Column('price_from', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amenities', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotels'))
    )
    op.create_index(op.f('ix_hotels_city'), 'hotels', ['city'], unique=False)
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.create_index(op.f('ix_hotels_is_active'), 'hotels', ['is_active'], unique=False)
    op.create_index(op.f('ix_hotels_price_level'), 'hotels', ['price_level'], unique=False)
    op.create_index(op.f('ix_hotels_slug'), 'hotels', ['slug'], unique=True)
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('price_level', sa.String(length=20), nullable=False),
    sa.Column('average_check', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_places'))
    )
    op.create_index(op.f('ix_places_city'), 'places', ['city'], unique=False)
    op.create_index(op.f('ix_places_id'), 'places', ['id'], unique=False)
    op.create_index(op.f('ix_places_is_active'), 'places', ['is_active'], unique=False)
    op.create_index(op.f('ix_places_price_level'), 'places', ['price_level'], unique=False)
    op.create_index(op.f('ix_places_slug'), 'places', ['slug'], unique=True)
    op.create_index(op.f('ix_places_type'), 'places', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('budget', sa.String(length=50), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('travel_style', sa.String(length=100), nullable=False),
    sa.Column('itinerary_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trips_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips'))
    )
    op.create_index(op.f('ix_trips_created_at'), 'trips', ['created_at'], unique=False)
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_index(op.f('ix_trips_title'), 'trips', ['title'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_table('trip_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_messages_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_messages'))
    )
    op.create_index(op.f('ix_trip_messages_created_at'), 'trip_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_trip_messages_id'), 'trip_messages', ['id'], unique=False)
    op.create_index(op.f('ix_trip_messages_trip_id'), 'trip_messages', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_messages_trip_id'), table_name='trip_messages')
    op.drop_index(op.f('ix_trip_messages_id'), table_name='trip_messages')
    op.drop_index(op.f('ix_trip_messages_created_at'), table_name='trip_messages')
    op.drop_table('trip_messages')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_title'), table_name='trips')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_created_at'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_places_type'), table_name='places')
    op.drop_index(op.f('ix_places_slug'), table_name='places')
    op.drop_index(op.f('ix_places_price_level'), table_name='places')
    op.drop_index(op.f('ix_places_is_active'), table_name='places')
    op.drop_index(op.f('ix_places_id'), table_name='places')
    op.drop_index(op.f('ix_places_city'), table_name='places')
    op.drop_table('places')
    op.drop_index(op.f('ix_hotels_slug'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_price_level'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_is_active'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_city'), table_name='hotels')
    op.drop_table('hotels')
    # ### end Alembic commands ###
