"""initial

Revision ID: 9c9850d9a88b
Revises: 
Create Date: 2026-04-23 06:21:29.909568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c9850d9a88b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('price_level', sa.String(length=20), nullable=False),
    sa.Column('price_from', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amenities', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotels'))
    )
    op.create_index(op.f('ix_hotels_city'), 'hotels', ['city'], unique=False)
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.create_index(op.f('ix_hotels_is_active'), 'hotels', ['is_active'], unique=False)
    op.create_index(op.f('ix_hotels_price_level'), 'hotels', ['price_level'], unique=False)
    op.create_index(op.f('ix_hotels_slug'), 'hotels', ['slug'], unique=True)
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('price_level', sa.String(length=20), nullable=False),
    sa.Column('average_check', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_places'))
    )
    op.create_index(op.f('ix_places_city'), 'places', ['city'], unique=False)
    op.create_index(op.f('ix_places_id'), 'places', ['id'], unique=False)
    op.create_index(op.f('ix_places_is_active'), 'places', ['is_active'], unique=False)
    op.create_index(op.f('ix_places_price_level'), 'places', ['price_level'], unique=False)
    op.create_index(op.f('ix_places_slug'), 'places', ['slug'], unique=True)
    op.create_index(op.f('ix_places_type'), 'places', ['type'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('FREE', 'PRO_MONTHLY', 'PRO_YEARLY', name='subscriptionplanname', native_enum=False), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('billing_period', sa.Enum('FREE', 'MONTHLY', 'YEARLY', 'LIFETIME', name='billingperiod', native_enum=False), nullable=False),
    sa.Column('trip_limit_per_day', sa.Integer(), nullable=False),
    sa.Column('chat_edit_limit_per_day', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans'))
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_is_active'), 'subscription_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'BUSINESS', name='userrole', native_enum=False), server_default=sa.text("'user'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_businesses_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_businesses'))
    )
    op.create_index(op.f('ix_businesses_created_at'), 'businesses', ['created_at'], unique=False)
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_index(op.f('ix_businesses_is_active'), 'businesses', ['is_active'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_index(op.f('ix_businesses_owner_id'), 'businesses', ['owner_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('budget', sa.String(length=50), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('travel_style', sa.String(length=100), nullable=False),
    sa.Column('itinerary_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trips_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips'))
    )
    op.create_index(op.f('ix_trips_created_at'), 'trips', ['created_at'], unique=False)
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_index(op.f('ix_trips_title'), 'trips', ['title'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELED', name='usersubscriptionstatus', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name=op.f('fk_user_subscriptions_plan_id_subscription_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_subscriptions'))
    )
    op.create_index(op.f('ix_user_subscriptions_created_at'), 'user_subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_expires_at'), 'user_subscriptions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_plan_id'), 'user_subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_started_at'), 'user_subscriptions', ['started_at'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_status'), 'user_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    op.create_table('user_usage_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('trip_generations_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('chat_edits_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_usage_stats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_usage_stats')),
    sa.UniqueConstraint('user_id', 'date', name=op.f('uq_user_usage_stats_user_id'))
    )
    op.create_index(op.f('ix_user_usage_stats_created_at'), 'user_usage_stats', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_usage_stats_date'), 'user_usage_stats', ['date'], unique=False)
    op.create_index(op.f('ix_user_usage_stats_id'), 'user_usage_stats', ['id'], unique=False)
    op.create_index(op.f('ix_user_usage_stats_user_id'), 'user_usage_stats', ['user_id'], unique=False)
    op.create_table('business_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('IMAGE', 'LOGO', name='businessmediatype', native_enum=False), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_media_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_media'))
    )
    op.create_index(op.f('ix_business_media_business_id'), 'business_media', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_media_created_at'), 'business_media', ['created_at'], unique=False)
    op.create_index(op.f('ix_business_media_id'), 'business_media', ['id'], unique=False)
    op.create_index(op.f('ix_business_media_type'), 'business_media', ['type'], unique=False)
    op.create_table('sponsored_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('google_place_id', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('cta_text', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('is_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_sponsored_places_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sponsored_places'))
    )
    op.create_index(op.f('ix_sponsored_places_business_id'), 'sponsored_places', ['business_id'], unique=False)
    op.create_index(op.f('ix_sponsored_places_category'), 'sponsored_places', ['category'], unique=False)
    op.create_index(op.f('ix_sponsored_places_city'), 'sponsored_places', ['city'], unique=False)
    op.create_index(op.f('ix_sponsored_places_created_at'), 'sponsored_places', ['created_at'], unique=False)
    op.create_index(op.f('ix_sponsored_places_google_place_id'), 'sponsored_places', ['google_place_id'], unique=False)
    op.create_index(op.f('ix_sponsored_places_id'), 'sponsored_places', ['id'], unique=False)
    op.create_index(op.f('ix_sponsored_places_is_active'), 'sponsored_places', ['is_active'], unique=False)
    op.create_index(op.f('ix_sponsored_places_is_approved'), 'sponsored_places', ['is_approved'], unique=False)
    op.create_index(op.f('ix_sponsored_places_title'), 'sponsored_places', ['title'], unique=False)
    op.create_table('trip_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_messages_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_messages'))
    )
    op.create_index(op.f('ix_trip_messages_created_at'), 'trip_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_trip_messages_id'), 'trip_messages', ['id'], unique=False)
    op.create_index(op.f('ix_trip_messages_trip_id'), 'trip_messages', ['trip_id'], unique=False)
    op.create_table('sponsored_impressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('sponsored_place_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_sponsored_impressions_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sponsored_place_id'], ['sponsored_places.id'], name=op.f('fk_sponsored_impressions_sponsored_place_id_sponsored_places'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_sponsored_impressions_trip_id_trips'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sponsored_impressions'))
    )
    op.create_index(op.f('ix_sponsored_impressions_business_id'), 'sponsored_impressions', ['business_id'], unique=False)
    op.create_index(op.f('ix_sponsored_impressions_city'), 'sponsored_impressions', ['city'], unique=False)
    op.create_index(op.f('ix_sponsored_impressions_created_at'), 'sponsored_impressions', ['created_at'], unique=False)
    op.create_index(op.f('ix_sponsored_impressions_day_number'), 'sponsored_impressions', ['day_number'], unique=False)
    op.create_index(op.f('ix_sponsored_impressions_id'), 'sponsored_impressions', ['id'], unique=False)
    op.create_index(op.f('ix_sponsored_impressions_sponsored_place_id'), 'sponsored_impressions', ['sponsored_place_id'], unique=False)
    op.create_index(op.f('ix_sponsored_impressions_trip_id'), 'sponsored_impressions', ['trip_id'], unique=False)
    op.create_table('sponsored_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('sponsored_place_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.Enum('CLICK', 'OPEN_WEBSITE', 'OPEN_MAP', 'CALL', 'SAVE', name='sponsoredinteractiontype', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_sponsored_interactions_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sponsored_place_id'], ['sponsored_places.id'], name=op.f('fk_sponsored_interactions_sponsored_place_id_sponsored_places'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_sponsored_interactions_trip_id_trips'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sponsored_interactions'))
    )
    op.create_index(op.f('ix_sponsored_interactions_business_id'), 'sponsored_interactions', ['business_id'], unique=False)
    op.create_index(op.f('ix_sponsored_interactions_created_at'), 'sponsored_interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_sponsored_interactions_id'), 'sponsored_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_sponsored_interactions_interaction_type'), 'sponsored_interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_sponsored_interactions_sponsored_place_id'), 'sponsored_interactions', ['sponsored_place_id'], unique=False)
    op.create_index(op.f('ix_sponsored_interactions_trip_id'), 'sponsored_interactions', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sponsored_interactions_trip_id'), table_name='sponsored_interactions')
    op.drop_index(op.f('ix_sponsored_interactions_sponsored_place_id'), table_name='sponsored_interactions')
    op.drop_index(op.f('ix_sponsored_interactions_interaction_type'), table_name='sponsored_interactions')
    op.drop_index(op.f('ix_sponsored_interactions_id'), table_name='sponsored_interactions')
    op.drop_index(op.f('ix_sponsored_interactions_created_at'), table_name='sponsored_interactions')
    op.drop_index(op.f('ix_sponsored_interactions_business_id'), table_name='sponsored_interactions')
    op.drop_table('sponsored_interactions')
    op.drop_index(op.f('ix_sponsored_impressions_trip_id'), table_name='sponsored_impressions')
    op.drop_index(op.f('ix_sponsored_impressions_sponsored_place_id'), table_name='sponsored_impressions')
    op.drop_index(op.f('ix_sponsored_impressions_id'), table_name='sponsored_impressions')
    op.drop_index(op.f('ix_sponsored_impressions_day_number'), table_name='sponsored_impressions')
    op.drop_index(op.f('ix_sponsored_impressions_created_at'), table_name='sponsored_impressions')
    op.drop_index(op.f('ix_sponsored_impressions_city'), table_name='sponsored_impressions')
    op.drop_index(op.f('ix_sponsored_impressions_business_id'), table_name='sponsored_impressions')
    op.drop_table('sponsored_impressions')
    op.drop_index(op.f('ix_trip_messages_trip_id'), table_name='trip_messages')
    op.drop_index(op.f('ix_trip_messages_id'), table_name='trip_messages')
    op.drop_index(op.f('ix_trip_messages_created_at'), table_name='trip_messages')
    op.drop_table('trip_messages')
    op.drop_index(op.f('ix_sponsored_places_title'), table_name='sponsored_places')
    op.drop_index(op.f('ix_sponsored_places_is_approved'), table_name='sponsored_places')
    op.drop_index(op.f('ix_sponsored_places_is_active'), table_name='sponsored_places')
    op.drop_index(op.f('ix_sponsored_places_id'), table_name='sponsored_places')
    op.drop_index(op.f('ix_sponsored_places_google_place_id'), table_name='sponsored_places')
    op.drop_index(op.f('ix_sponsored_places_created_at'), table_name='sponsored_places')
    op.drop_index(op.f('ix_sponsored_places_city'), table_name='sponsored_places')
    op.drop_index(op.f('ix_sponsored_places_category'), table_name='sponsored_places')
    op.drop_index(op.f('ix_sponsored_places_business_id'), table_name='sponsored_places')
    op.drop_table('sponsored_places')
    op.drop_index(op.f('ix_business_media_type'), table_name='business_media')
    op.drop_index(op.f('ix_business_media_id'), table_name='business_media')
    op.drop_index(op.f('ix_business_media_created_at'), table_name='business_media')
    op.drop_index(op.f('ix_business_media_business_id'), table_name='business_media')
    op.drop_table('business_media')
    op.drop_index(op.f('ix_user_usage_stats_user_id'), table_name='user_usage_stats')
    op.drop_index(op.f('ix_user_usage_stats_id'), table_name='user_usage_stats')
    op.drop_index(op.f('ix_user_usage_stats_date'), table_name='user_usage_stats')
    op.drop_index(op.f('ix_user_usage_stats_created_at'), table_name='user_usage_stats')
    op.drop_table('user_usage_stats')
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_status'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_started_at'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_plan_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_expires_at'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_created_at'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_title'), table_name='trips')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_created_at'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_businesses_owner_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_is_active'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_created_at'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_is_active'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_places_type'), table_name='places')
    op.drop_index(op.f('ix_places_slug'), table_name='places')
    op.drop_index(op.f('ix_places_price_level'), table_name='places')
    op.drop_index(op.f('ix_places_is_active'), table_name='places')
    op.drop_index(op.f('ix_places_id'), table_name='places')
    op.drop_index(op.f('ix_places_city'), table_name='places')
    op.drop_table('places')
    op.drop_index(op.f('ix_hotels_slug'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_price_level'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_is_active'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_city'), table_name='hotels')
    op.drop_table('hotels')
    # ### end Alembic commands ###
